// Six scenarios, each exercising a distinct branch of the rebooking/refund decision tree.
const hours = (n) => n * 60 * 60 * 1000;
const now = Date.now();
const dep = (offsetHours) => new Date(now + hours(offsetHours));

export const passengers = [
  { key: "A", firstName: "Aarav", lastName: "Shah", email: "aarav.shah@example.com", phone: "+91-90000-00001" },
  { key: "B", firstName: "Bella", lastName: "Fernandes", email: "bella.f@example.com", phone: "+91-90000-00002" },
  { key: "C", firstName: "Chirag", lastName: "Mehta", email: "chirag.mehta@example.com", phone: "+91-90000-00003" },
  { key: "D", firstName: "Divya", lastName: "Nair", email: "divya.nair@example.com", phone: "+91-90000-00004" },
  { key: "E", firstName: "Ethan", lastName: "Rodrigues", email: "ethan.r@example.com", phone: "+91-90000-00005" },
  { key: "F", firstName: "Farah", lastName: "Khan", email: "farah.khan@example.com", phone: "+91-90000-00006" },
];

export const flights = [
  // Scenario 1: on-time
  {
    key: "SJ100",
    flightNumber: "SJ100",
    origin: "BOM",
    destination: "DEL",
    departureTime: dep(6),
    arrivalTime: dep(8),
    status: "on-time",
    cabinClasses: ["economy", "business"],
    fareType: "standard",
    international: false,
    seatsAvailable: { economy: 20, business: 4 },
    disruptionType: "none",
    delayMinutes: 0,
    reason: "",
    gate: "A3",
    terminal: "T1",
  },
  // Scenario 2: delayed
  {
    key: "SJ150",
    flightNumber: "SJ150",
    origin: "BLR",
    destination: "HYD",
    departureTime: dep(10),
    arrivalTime: dep(11.5),
    status: "delayed",
    cabinClasses: ["economy"],
    fareType: "standard",
    international: false,
    seatsAvailable: { economy: 15 },
    disruptionType: "weather",
    delayMinutes: 95,
    reason: "Heavy monsoon activity at BLR delaying departure",
    gate: "C7",
    terminal: "T2",
  },
  // Scenario 3: cancelled, auto-rebook eligible (alternates below)
  {
    key: "SJ200",
    flightNumber: "SJ200",
    origin: "BOM",
    destination: "GOI",
    departureTime: dep(5),
    arrivalTime: dep(6.5),
    status: "cancelled",
    cabinClasses: ["economy", "business"],
    fareType: "standard",
    international: false,
    seatsAvailable: { economy: 0, business: 0 },
    disruptionType: "technical",
    delayMinutes: 0,
    reason: "Aircraft technical inspection required",
    gate: "B12",
    terminal: "T2",
  },
  { key: "SJ201-ALT", flightNumber: "SJ201", origin: "BOM", destination: "GOI", departureTime: dep(9), arrivalTime: dep(10.5), status: "on-time", cabinClasses: ["economy", "business"], fareType: "standard", international: false, seatsAvailable: { economy: 12, business: 2 }, disruptionType: "none", delayMinutes: 0, reason: "", gate: "B14", terminal: "T2" },
  { key: "SJ202-ALT", flightNumber: "SJ202", origin: "BOM", destination: "GOI", departureTime: dep(14), arrivalTime: dep(15.5), status: "on-time", cabinClasses: ["economy", "business"], fareType: "standard", international: false, seatsAvailable: { economy: 8, business: 1 }, disruptionType: "none", delayMinutes: 0, reason: "", gate: "B16", terminal: "T2" },
  // Scenario 4: cancelled, no good alternate -> escalate
  {
    key: "SJ300",
    flightNumber: "SJ300",
    origin: "PNQ",
    destination: "IXC",
    departureTime: dep(7),
    arrivalTime: dep(9),
    status: "cancelled",
    cabinClasses: ["economy"],
    fareType: "standard",
    international: false,
    seatsAvailable: { economy: 0 },
    disruptionType: "seat-unavailable",
    delayMinutes: 0,
    reason: "Equipment swap resulted in reduced capacity; no seats available on remaining flights",
    gate: "D2",
    terminal: "T1",
  },
  { key: "SJ301-ALT-FULL", flightNumber: "SJ301", origin: "PNQ", destination: "IXC", departureTime: dep(11), arrivalTime: dep(13), status: "on-time", cabinClasses: ["economy"], fareType: "standard", international: false, seatsAvailable: { economy: 0 }, disruptionType: "none", delayMinutes: 0, reason: "", gate: "D4", terminal: "T1" },
  // Scenario 5: cancelled, international/special fare -> forced escalation
  {
    key: "SJ400",
    flightNumber: "SJ400",
    origin: "BOM",
    destination: "DXB",
    departureTime: dep(8),
    arrivalTime: dep(11),
    status: "cancelled",
    cabinClasses: ["economy", "business"],
    fareType: "special",
    international: true,
    seatsAvailable: { economy: 0, business: 0 },
    disruptionType: "crew-unavailable",
    delayMinutes: 0,
    reason: "Crew duty-time limits reached ahead of international departure",
    gate: "E5",
    terminal: "T3",
  },
  { key: "SJ401-ALT", flightNumber: "SJ401", origin: "BOM", destination: "DXB", departureTime: dep(12), arrivalTime: dep(15), status: "on-time", cabinClasses: ["economy", "business"], fareType: "standard", international: true, seatsAvailable: { economy: 10, business: 3 }, disruptionType: "none", delayMinutes: 0, reason: "", gate: "E7", terminal: "T3" },
  // Scenario 6: cancelled, standard fare, refund-eligible
  {
    key: "SJ500",
    flightNumber: "SJ500",
    origin: "CCU",
    destination: "MAA",
    departureTime: dep(4),
    arrivalTime: dep(6),
    status: "cancelled",
    cabinClasses: ["economy"],
    fareType: "standard",
    international: false,
    seatsAvailable: { economy: 0 },
    disruptionType: "technical",
    delayMinutes: 0,
    reason: "Mechanical fault detected during pre-flight check",
    gate: "F1",
    terminal: "T1",
  },
];

export const bookings = [
  { key: "1", pnr: "SJONT1", passengerKey: "A", flightKey: "SJ100", cabin: "economy" },
  { key: "2", pnr: "SJDLY1", passengerKey: "B", flightKey: "SJ150", cabin: "economy" },
  { key: "3", pnr: "SJRBK1", passengerKey: "C", flightKey: "SJ200", cabin: "economy" },
  { key: "4", pnr: "SJESC1", passengerKey: "D", flightKey: "SJ300", cabin: "economy" },
  { key: "5", pnr: "SJINT1", passengerKey: "E", flightKey: "SJ400", cabin: "business" },
  { key: "6", pnr: "SJRFD1", passengerKey: "F", flightKey: "SJ500", cabin: "economy" },
];
